version: '3.9'

services:
  app:
    build: .
    container_name: php-app
    restart: unless-stopped
    ports:
      - '8001:80'
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: postgres-db
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
    driver: local
